// Crest data extracted from items.json (slotType === CREST)
const CREST_DATA = {
"Liberator":{"p":0,"r":"L","s":"C","st":["+12 Physical Power","15% Attack Speed","7% Lifesteal"],"fx":[{"n":"","t":"","a":true,"cd":"180s"}]},
"Sharpshooter Crest":{"p":0,"r":"L","s":"C","st":["+8 Physical Power","10% Attack Speed","5% Lifesteal"],"fx":[{"n":"","t":""}]},
"Typhoon":{"p":0,"r":"L","s":"C","st":["+30 Magical Power","+100 Health","+8 Ability Haste"],"fx":[{"n":"","t":""},{"n":"","t":"","cd":"35s"}]},
"Epoch":{"p":0,"r":"L","s":"C","st":["+30 Magical Power","+200 Mana","+8 Ability Haste"],"fx":[{"n":"","t":"","a":true,"cd":"165s"}]},
"Iceskorn Talons":{"p":0,"r":"L","s":"C","st":["+12 Physical Power","+100 Health","4% Omnivamp"],"fx":[{"n":"","t":"","a":true,"cd":"45s"}]},
"Judgement":{"p":0,"r":"L","s":"C","st":["+12 Physical Power","+100 Health","4% Omnivamp"],"fx":[{"n":"","t":"","a":true,"cd":"24-10s"}]},
"Witchstalker":{"p":0,"r":"L","s":"C","st":["+12 Physical Power","+5 Physical Penetration","+8 Ability Haste"],"fx":[{"n":"","t":"","a":true,"cd":"165s"}]},
"Soulbearer":{"p":0,"r":"L","s":"C","st":["+30 Magical Power","+200 Mana","+8 Ability Haste"],"fx":[{"n":"","t":"","a":true,"cd":"120s"}]},
"Pacifier":{"p":0,"r":"L","s":"C","st":["+12 Physical Power","15% Attack Speed","7% Lifesteal"],"fx":[{"n":"","t":"","a":true,"cd":"135s"}]},
"Magician Crest":{"p":0,"r":"L","s":"C","st":["+8 Magical Power","+80 Mana","+4 Ability Haste"],"fx":[{"n":"","t":""}]},
"Florescence":{"p":0,"r":"L","s":"C","st":["+120 Health","50% Base Health Regeneration","+2 Gold Per Second"],"fx":[{"n":"","t":"","a":true,"cd":"75s"},{"n":"","t":""},{"n":"","t":""}]},
"Assassin Crest":{"p":0,"r":"L","s":"C","st":["+6 Physical Power","+3 Physical Penetration","+6 Ability Haste"],"fx":[{"n":"","t":""}]},
"Marksman Crest":{"p":0,"r":"L","s":"C","st":["+4 Physical Power","5% Attack Speed","3% Lifesteal"],"fx":[{"n":"","t":""}]},
"Nyr Warboots":{"p":0,"r":"L","s":"C","st":["+180 Health","+8 Physical Armor","+5 Magical Armor"],"fx":[{"n":"","t":"","a":true,"cd":"75s"}]},
"Tranquility":{"p":0,"r":"L","s":"C","st":["+100 Health","40% Base Mana Regeneration","+2 Gold Per Second"],"fx":[{"n":"","t":"","a":true,"cd":"40s"},{"n":"","t":""},{"n":"","t":""}]},
"Warden Crest":{"p":0,"r":"L","s":"C","st":["+80 Health","30% Base Health Regeneration","+0.5 Gold Per Second"],"fx":[{"n":"","t":""},{"n":"","t":""}]},
"Exodus":{"p":0,"r":"L","s":"C","st":["+12 Physical Power","15% Attack Speed","7% Lifesteal"],"fx":[{"n":"","t":"","a":true,"cd":"120s"}]},
"Titan Crest":{"p":0,"r":"L","s":"C","st":["+60 Health","+4 Physical Armor","+2 Magical Armor"],"fx":[{"n":"","t":""}]},
"Occult Crest":{"p":0,"r":"L","s":"C","st":["+8 Magical Power","+50 Health","+4 Ability Haste"],"fx":[{"n":"","t":""}]},
"Nex":{"p":0,"r":"L","s":"C","st":["+12 Physical Power","+5 Physical Penetration","+8 Ability Haste"],"fx":[{"n":"","t":"","a":true,"cd":"90s"},{"n":"","t":""}]},
"Gravitum":{"p":0,"r":"L","s":"C","st":["+12 Physical Power","+100 Health","4% Omnivamp"],"fx":[{"n":"","t":"","a":true,"cd":"90s"}]},
"Consort Crest":{"p":0,"r":"L","s":"C","st":["+40 Health","25% Base Mana Regeneration","+0.4 Gold Per Second"],"fx":[{"n":"","t":""},{"n":"","t":""}]},
"Champion Crest":{"p":0,"r":"L","s":"C","st":["+8 Physical Power","+75 Health","3% Omnivamp"],"fx":[{"n":"","t":""}]},
"Rift Walkers":{"p":0,"r":"L","s":"C","st":["+120 Health","50% Base Health Regeneration","+2 Gold Per Second"],"fx":[{"n":"","t":"","a":true,"cd":"120s"},{"n":"","t":""},{"n":"","t":""}]},
"Sanctification":{"p":0,"r":"L","s":"C","st":["+120 Health","50% Base Health Regeneration","+2 Gold Per Second"],"fx":[{"n":"","t":"","a":true,"cd":"120s"},{"n":"","t":""},{"n":"","t":""}]},
"Pygmy Dust":{"p":0,"r":"L","s":"C","st":["+100 Health","40% Base Mana Regeneration","+2 Gold Per Second"],"fx":[{"n":"","t":"","a":true,"cd":"120s"},{"n":"","t":""},{"n":"","t":""}]},
"Voidgazer":{"p":0,"r":"L","s":"C","st":["+30 Magical Power","+200 Mana","+8 Ability Haste"],"fx":[{"n":"","t":"","a":true,"cd":"100s"}]},
"Time-Flux Band":{"p":0,"r":"L","s":"C","st":["+30 Magical Power","+200 Mana","+8 Ability Haste"],"fx":[{"n":"","t":"","a":true,"cd":"120s"}]},
"Saphir's Mantle":{"p":0,"r":"L","s":"C","st":["+180 Health","+8 Physical Armor","+5 Magical Armor"],"fx":[{"n":"","t":"","a":true,"cd":"75s"}]},
"Winter's Fury":{"p":0,"r":"L","s":"C","st":["+30 Magical Power","+100 Health","+8 Ability Haste"],"fx":[{"n":"","t":"","a":true,"cd":"105s"}]},
"Brutallax":{"p":0,"r":"L","s":"C","st":["+12 Physical Power","+100 Health","4% Omnivamp"],"fx":[{"n":"","t":"","a":true,"cd":"165s"}]},
"Warlock Crest":{"p":0,"r":"L","s":"C","st":["+15 Magical Power","+80 Health","+6 Ability Haste"],"fx":[{"n":"","t":""}]},
"Ortus":{"p":0,"r":"L","s":"C","st":["+12 Physical Power","+5 Physical Penetration","+8 Ability Haste"],"fx":[{"n":"","t":"","a":true,"cd":"90s"}]},
"Obelisk":{"p":0,"r":"L","s":"C","st":["+30 Magical Power","+100 Health","+8 Ability Haste"],"fx":[{"n":"","t":"","a":true,"cd":"15s"},{"n":"","t":""}]},
"Abyssal Dart":{"p":0,"r":"L","s":"C","st":["+12 Physical Power","+5 Physical Penetration","+8 Ability Haste"],"fx":[{"n":"","t":"","a":true,"cd":"90s"}]},
"Earth Spirit":{"p":0,"r":"L","s":"C","st":["+180 Health","+8 Physical Armor","+5 Magical Armor"],"fx":[{"n":"","t":"","a":true,"cd":"165s"}]},
"Tempest":{"p":0,"r":"L","s":"C","st":["+30 Magical Power","+100 Health","+8 Ability Haste"],"fx":[{"n":"","t":"","a":true,"cd":"90s"}]},
"Razorback":{"p":0,"r":"L","s":"C","st":["+180 Health","+8 Physical Armor","+5 Magical Armor"],"fx":[{"n":"","t":"","a":true,"cd":"90s"}]},
"Warrior Crest":{"p":0,"r":"L","s":"C","st":["+5 Physical Power","+50 Health","2% Omnivamp"],"fx":[{"n":"","t":""}]},
"Silentium":{"p":0,"r":"L","s":"C","st":["+100 Health","40% Base Mana Regeneration","+2 Gold Per Second"],"fx":[{"n":"","t":"","a":true,"cd":"120s"},{"n":"","t":""},{"n":"","t":""}]},
"Rogue Crest":{"p":0,"r":"L","s":"C","st":["+3 Physical Power","+2 Physical Penetration","+4 Ability Haste"],"fx":[{"n":"","t":""}]},
"Goliath Crest":{"p":0,"r":"L","s":"C","st":["+90 Health","+6 Physical Armor","+3 Magical Armor"],"fx":[{"n":"","t":""}]},
"Reclamation":{"p":0,"r":"L","s":"C","st":["+100 Health","40% Base Mana Regeneration","+2 Gold Per Second"],"fx":[{"n":"","t":"","a":true,"cd":"180s"},{"n":"","t":""},{"n":"","t":""}]},
"Keeper Crest":{"p":0,"r":"L","s":"C","st":["+80 Health","35% Base Mana Regeneration","+0.5 Gold Per Second"],"fx":[{"n":"","t":""},{"n":"","t":""}]},
"Guardian Crest":{"p":0,"r":"L","s":"C","st":["+40 Health","20% Base Health Regeneration","+0.4 Gold Per Second"],"fx":[{"n":"","t":""},{"n":"","t":""}]},
"Leafsong":{"p":0,"r":"L","s":"C","st":["+120 Health","50% Base Health Regeneration","+2 Gold Per Second"],"fx":[{"n":"","t":"","a":true,"cd":"100s"},{"n":"","t":""},{"n":"","t":""}]},
"Wizard Crest":{"p":0,"r":"L","s":"C","st":["+15 Magical Power","+125 Mana","+6 Ability Haste"],"fx":[{"n":"","t":""}]},
"Eviscerator":{"p":0,"r":"L","s":"C","st":["+12 Physical Power","15% Attack Speed","7% Lifesteal"],"fx":[{"n":"","t":"","a":true,"cd":"90s"}]},
};