// Manual crest classification - identity, buy tips, counter tips
// Crests are free (0g) and occupy a separate slot
const CREST_TIPS = {

// ── Base Crests (Tier 1 → Tier 2) ──
'Marksman Crest':    { id: 'Base ADC crest, evolves via basic attacks', tags: ['carry', 'evolving', 'sustain'], buy: 'Default starting crest for auto-attack carries in duo lane.', tip: 'Weakest crest stats in the game early — punish the carry before they evolve at ~3-4 min.' },
'Rogue Crest':       { id: 'Base physical assassin/caster crest', tags: ['assassin', 'evolving', 'sustain'], buy: 'Starting crest for ability-based physical assassins and junglers.', tip: 'Low stats early; if they\'re slow to evolve they\'ll be behind on crest power spikes.' },
'Warrior Crest':     { id: 'Base fighter/bruiser crest', tags: ['fighter', 'evolving', 'sustain'], buy: 'Starting crest for offlane bruisers and fighters who deal sustained damage.', tip: 'Omnivamp sustain is weak early — trade aggressively before they evolve.' },
'Titan Crest':       { id: 'Base tank crest, evolves by taking damage', tags: ['tank', 'evolving', 'sustain'], buy: 'Starting crest for pure tanks who expect to soak damage.', tip: 'Evolves passively from taking damage — they WANT to trade, so don\'t give free poke that fuels evolution.' },
'Magician Crest':    { id: 'Base mage crest, evolves via mana restore', tags: ['mage', 'evolving', 'sustain'], buy: 'Default starting crest for ability-based mages in mid lane.', tip: 'Mana restore evolution means they want to spam abilities — dodge skillshots to slow their evolution.' },
'Occult Crest':      { id: 'Base hybrid mage/fighter crest', tags: ['mage', 'fighter', 'evolving', 'sustain'], buy: 'Starting crest for AP bruisers and jungle mages who deal ability damage.', tip: 'Similar to Rogue but for magic damage dealers — health restore on ability hits fuels evolution.' },
'Guardian Crest':    { id: 'Base support crest (heal-focused)', tags: ['support', 'evolving', 'sustain'], buy: 'Starting crest for heal/shield supports who poke with abilities.', tip: 'Needs a nearby ally to proc charges — zone the support away from their carry to deny gold and evolution.' },
'Consort Crest':     { id: 'Base support crest (damage-focused)', tags: ['support', 'evolving', 'sustain'], buy: 'Starting crest for aggressive poke supports who want damage procs.', tip: 'Deals bonus damage on charge procs — respect the poke, especially with 3 charges stacked.' },

// ── Mid-Tier Crests (Tier 2 → Legendary) ──
'Sharpshooter Crest': { id: 'Evolved Marksman, pre-legendary carry crest', tags: ['carry', 'evolving', 'sustain'], buy: 'Auto-evolves from Marksman Crest — pick your legendary wisely based on matchup.', tip: 'Second evolution requires returning to base — a well-timed fight can delay their legendary crest.', evolves_from: 'Marksman Crest' },
'Assassin Crest':    { id: 'Evolved Rogue, pre-legendary assassin crest', tags: ['assassin', 'evolving', 'sustain'], buy: 'Auto-evolves from Rogue — start planning your legendary choice based on enemy comp.', tip: 'Must recall to evolve into legendary — punish the recall window.', evolves_from: 'Rogue Crest' },
'Champion Crest':    { id: 'Evolved Warrior, pre-legendary bruiser crest', tags: ['fighter', 'evolving', 'sustain'], buy: 'Auto-evolves from Warrior — stronger omnivamp sustain in lane.', tip: 'Must recall for legendary evolution — force fights to delay their power spike.', evolves_from: 'Warrior Crest' },
'Goliath Crest':     { id: 'Evolved Titan, pre-legendary tank crest', tags: ['tank', 'evolving', 'sustain'], buy: 'Auto-evolves from Titan — beefier stats while working toward legendary.', tip: 'Still evolves passively from taking damage — anti-heal reduces the healing that counts toward evolution.', evolves_from: 'Titan Crest' },
'Wizard Crest':      { id: 'Evolved Magician, pre-legendary mage crest', tags: ['mage', 'evolving', 'sustain'], buy: 'Auto-evolves from Magician — more mana sustain for extended laning.', tip: 'Must recall for legendary — pressure mid to deny the free back timing.', evolves_from: 'Magician Crest' },
'Warlock Crest':     { id: 'Evolved Occult, pre-legendary AP bruiser crest', tags: ['mage', 'fighter', 'evolving', 'sustain'], buy: 'Auto-evolves from Occult — better stats for AP junglers mid-clear.', tip: 'Must recall for legendary evolution — invade or contest objectives during their recall window.', evolves_from: 'Occult Crest' },
'Keeper Crest':      { id: 'Evolved support crest (from both Guardian & Consort)', tags: ['support', 'evolving', 'sustain'], buy: 'Auto-evolves from Guardian or Consort — both paths merge here before legendary.', tip: 'Still charge-based with Pacifist — denying lane pressure slows gold and evolution.', evolves_from: 'Guardian Crest' },
'Warden Crest':      { id: 'Evolved support crest (tank support path)', tags: ['support', 'tank', 'evolving', 'sustain'], buy: 'Alternative evolved support crest for tank supports who want health restore over damage.', tip: 'Restores 30 HP per charge proc — more survivable in trades than Keeper path.', evolves_from: 'Guardian Crest' },

// ── Legendary Carry Crests ──
'Liberator':         { id: 'Carry cleanse + shield active', tags: ['carry', 'cleanse', 'shield', 'active'], buy: 'Pick when enemy has heavy CC that threatens you (Dekker, Riktor, Narbash stun).', tip: '180s CD cleanse — burn it with lesser CC then hard-engage within the 3-min window.' },
'Pacifier':          { id: 'Carry dash + execute active', tags: ['carry', 'mobility', 'burst', 'active'], buy: 'Pick when you need a dash for repositioning and can secure kills on low-HP targets.', tip: '2.5x damage below 20% HP is an execute — don\'t stay low. Resets on kill so it snowballs teamfights.' },
'Exodus':            { id: 'Carry displacement grenade', tags: ['carry', 'cc', 'active', 'peel'], buy: 'Pick for self-peel against divers or to create picks by knocking enemies into your team.', tip: 'Grenade explodes on terrain — position away from walls. Launched targets take 20% more damage for 1s.' },
'Eviscerator':       { id: 'Carry steroid active (AS + omnivamp + on-hit)', tags: ['carry', 'dps', 'sustain', 'active', 'on-hit'], buy: 'Pick for raw DPS increase in extended teamfights where you can free-hit.', tip: '90s CD steroid — disengage or burst them before 6s of empowered attacks shreds your team.' },

// ── Legendary Assassin/Fighter Crests ──
'Witchstalker':      { id: 'Assassin cleanse + %HP empowered strike', tags: ['assassin', 'cleanse', 'burst', 'active'], buy: 'Pick against CC-heavy comps — cleanse doubles the empowered damage if a debuff is removed.', tip: '4% max HP (8% if cleansed) + heal — don\'t stack CC on this target, bait the cleanse first.' },
'Nex':               { id: 'Assassin dash + stored damage nuke', tags: ['assassin', 'mobility', 'burst', 'active'], buy: 'Pick for burst assassins who deal front-loaded damage and want a dash finisher.', tip: 'Sow stores 18% of damage dealt — if they\'ve been poking, the Reap will hit HARD. 80% slow for 1s.' },
'Abyssal Dart':      { id: 'Assassin teleport-to-target dart', tags: ['assassin', 'mobility', 'burst', 'active'], buy: 'Pick for long-range picks — fire dart, then teleport to the marked target.', tip: 'Dart is a skillshot that pierces minions — sidestep it or the assassin gets a free gap close.' },
'Ortus':             { id: 'Assassin snowball active (MS + power, resets on kill)', tags: ['assassin', 'mobility', 'scaling', 'active'], buy: 'Pick when you expect to get resets — each takedown permanently grants 3 physical power.', tip: 'Permanently stacks power on kills — shut them down early or they scale out of control.' },

// ── Legendary Fighter/Bruiser Crests ──
'Judgement':         { id: 'Fighter AOE cleave + heal active', tags: ['fighter', 'sustain', 'aoe', 'active'], buy: 'Pick for melee fighters who brawl in the middle of teamfights and need AOE + sustain.', tip: '24-10s CD means it\'s up constantly in fights. Anti-heal is critical to counter the healing.' },
'Iceskorn Talons':   { id: 'Fighter team-buff ice zone', tags: ['fighter', 'aoe', 'active', 'buff'], buy: 'Pick when your team groups — 12% phys power + MS for allies, slow for enemies on 45s CD.', tip: 'Ice sheet lasts 8s — walk off it to avoid the slow. Allies on it get a significant power boost.' },
'Gravitum':          { id: 'Fighter ground-effect projectile (anti-dash)', tags: ['fighter', 'cc', 'active'], buy: 'Pick against mobile heroes — Grounds for 2.5s, preventing dashes and blinks.', tip: 'Infinite range piercing projectile — respect sightlines. Grounded means NO dashes for 2.5s.' },
'Brutallax':         { id: 'Fighter cleanse + tenacity steroid', tags: ['fighter', 'cleanse', 'active'], buy: 'Pick against heavy CC when you need to keep auto-attacking through crowd control.', tip: '60% tenacity for 4s, extended by autos — peel and kite, don\'t try to CC-lock this target.' },

// ── Legendary Tank Crests ──
'Nyr Warboots':      { id: 'Tank MS burst + health regen', tags: ['tank', 'mobility', 'sustain', 'active'], buy: 'Pick for engage tanks who need to close distance or disengage while regenerating.', tip: '50% decaying MS + 15% max HP regen over 5s — kite and wait it out, don\'t chase.' },
'Saphir\'s Mantle':  { id: 'Tank size increase + permanent HP scaling', tags: ['tank', 'scaling', 'active'], buy: 'Pick for front-line tanks who want permanent HP scaling from teamfight damage.', tip: 'Permanently gains max HP from damage dealt — gets tankier every fight. Focus carries, not this tank.' },
'Earth Spirit':      { id: 'Tank unstoppable boulder engage', tags: ['tank', 'cc', 'mobility', 'active'], buy: 'Pick for hard-engage tanks — unstoppable roll that stuns the first hero hit.', tip: 'Unstoppable means CC doesn\'t stop the roll — sidestep it. 45s CD reduction if they hit a hero.' },
'Razorback':         { id: 'Tank damage reflect + armor steroid', tags: ['tank', 'active', 'defense'], buy: 'Pick against heavy auto-attackers — 25% bonus armor + 15% damage reflect.', tip: 'Reflects 15% PRE-MITIGATION damage — carries hurt themselves hitting this. Focus someone else during active.' },

// ── Legendary Mage Crests ──
'Epoch':             { id: 'Mage Zhonya\'s stasis active', tags: ['mage', 'active', 'defense'], buy: 'Pick when you need invulnerability to survive burst or buy time for cooldowns.', tip: '165s CD stasis — bait it with poke then re-engage. They can\'t move or act during 2.5s.' },
'Soulbearer':        { id: 'Mage shield + lifesteal + MS steroid', tags: ['mage', 'shield', 'sustain', 'active'], buy: 'Pick for sustained mage fights — shield + 20% magical lifesteal + MS for 8s.', tip: 'Huge sustain window for 8s — burst through the shield or disengage and wait it out.' },
'Typhoon':           { id: 'Mage on-hit AS stacker with dash', tags: ['mage', 'on-hit', 'mobility', 'dps'], buy: 'Pick for auto-attack mages (Shinbi, Countess) who weave basics between abilities.', tip: 'At 4 Cyclone stacks they get a free dash on 35s CD — track the stacks and expect the reposition.' },
'Voidgazer':         { id: 'Mage damage amp projectile', tags: ['mage', 'burst', 'cc', 'active'], buy: 'Pick for burst mages who want to open with a slow + 15% damage amp before comboing.', tip: 'Pierces minions — don\'t hide behind waves. 15% damage amp for 3s makes follow-up abilities devastating.' },
'Time-Flux Band':    { id: 'Mage recall + CD reset active', tags: ['mage', 'mobility', 'cdr', 'active'], buy: 'Pick for aggressive dives — teleport back to safety after dumping abilities, with CDs reset.', tip: 'Marks location and teleports back after 4s — the mark is visible, so collapse on it to catch the return.' },
'Obelisk':           { id: 'Mage infinite-scaling soul collector', tags: ['mage', 'scaling', 'on-hit', 'active'], buy: 'Pick for farming mages who want permanent AP scaling — each soul = +1 magical power.', tip: 'Infinite scaling — late-game Obelisk mages hit extremely hard. End early or deny farm.' },
'Winter\'s Fury':    { id: 'Mage AOE slow + magic damage amp', tags: ['mage', 'aoe', 'cc', 'burst', 'active'], buy: 'Pick for teamfight mages who want AOE zone control with a damage amp.', tip: 'Expanding sphere over 3s — walk out immediately. 10% magic damage amp for 3s to anyone hit.' },
'Tempest':           { id: 'Mage sustained AOE damage + self-heal', tags: ['mage', 'aoe', 'sustain', 'active'], buy: 'Pick for brawler mages in extended fights — 7s of AOE damage with 30% healing.', tip: 'Hits 3 nearest heroes every second — spread out. Diminishing returns on repeat hits to same target.' },

// ── Legendary Support Crests ──
'Tranquility':       { id: 'Support AOE heal + damage mitigation', tags: ['support', 'sustain', 'active'], buy: 'Pick as the default healer support crest — 40s CD group heal with damage mitigation.', tip: '40s CD heal is very frequent — bait it before committing to an all-in. 10% mitigation for 2s.' },
'Sanctification':    { id: 'Support AOE shield + tenacity', tags: ['support', 'shield', 'active'], buy: 'Pick against CC-heavy comps — AOE shield that grants 45% tenacity while it holds.', tip: 'Shield must hold for tenacity — break it fast with burst to remove the tenacity buff.' },
'Reclamation':       { id: 'Support AOE cleanse', tags: ['support', 'cleanse', 'active'], buy: 'Pick against heavy CC/debuff comps — the only AOE cleanse in the game.', tip: '180s CD — burn it with lesser CC, then use your real engage. Extremely high-value cooldown.' },
'Silentium':         { id: 'Support targeted silence + damage', tags: ['support', 'cc', 'burst', 'active'], buy: 'Pick against ability-reliant heroes — 1s silence interrupts channels and combos.', tip: 'Point-and-click silence with 150 (+50%) damage — play around the 120s CD.' },
'Pygmy Dust':        { id: 'Support shrink (ally speed / enemy slow + damage reduction)', tags: ['support', 'cc', 'active', 'peel'], buy: 'Pick for versatile peel/engage — shrink allies for speed or enemies for slow + 30% less damage.', tip: 'Shrunk enemies deal 30% LESS damage for 3.5s — devastating if used on your carry. Cleanse removes it.' },
'Leafsong':          { id: 'Support team MS + slow immunity', tags: ['support', 'mobility', 'active'], buy: 'Pick for engage or disengage — 30% MS + slow immunity + unit phasing for 4s.', tip: 'Team can phase through heroes — body-blocking won\'t work during Phantom Rush. Wait out the 4s.' },
'Rift Walkers':      { id: 'Support dash + enemy pull', tags: ['support', 'cc', 'mobility', 'active'], buy: 'Pick for aggressive tank supports who want to dash in and displace enemies.', tip: 'Short dash + pull is telegraphed — sidestep or dash away when you see the support dash forward.' },
'Florescence':       { id: 'Support bouncy mushroom placement', tags: ['support', 'utility', 'active'], buy: 'Pick for creative zone control — Starshroom bounces heroes up, great for objectives and chokes.', tip: 'Mushroom lasts 120s — spot it and avoid jumping onto it. Disappears 10s after being bounced on.' },
};
